/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Desoc } from "./Desoc";
export type { Factory } from "./Factory";
export type { MetadataHolder } from "./MetadataHolder";
export * as factories from "./factories";
export { Factory__factory } from "./factories/Factory__factory";
export { Desoc__factory } from "./factories/Desoc__factory";
export { MetadataHolder__factory } from "./factories/MetadataHolder__factory";
