/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Desoc__factory } from "./Desoc__factory";
export { Factory__factory } from "./Factory__factory";
export { MetadataHolder__factory } from "./MetadataHolder__factory";
