export const IPFS_GATEWAY = process.env.NEXT_PUBLIC_IPFS_GATEWAY;
export const PINATA_IPFS_GATEWAY = process.env.NEXT_PUBLIC_PINATA_IPFS_GATEWAY;
export const W3S_IPFS_GATEWAY = process.env.NEXT_PUBLIC_W3SLINK_IPFS_GATEWAY;
export const WEB3_STORAGE_TOKEN = process.env.WEB3_STORAGE_TOKEN;
