/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDesoc__factory } from "./IDesoc__factory";
export { IMetaHolder__factory } from "./IMetaHolder__factory";
