import Launcher from 'components/Transactors/Launcher/Launcher';
import LaunchForm from 'components/Transactors/Launcher/LaunchForm';
import type { NextPage } from 'next';
import Head from 'next/head';

const Launch: NextPage = () => {
  return (
    <div className="py-0 px-10">
      <Head>
        <title>Credential Manager App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Launcher Form={LaunchForm} />
    </div>
  );
};

export default Launch;
