/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Desoc } from "./Desoc";
export type { Factory } from "./Factory";
export type { MetadataHolder } from "./MetadataHolder";
