/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IMetaHolderInterface extends utils.Interface {
  functions: {
    "addSociety(address,string)": FunctionFragment;
    "issueAttestation(uint256,uint256,address,address)": FunctionFragment;
    "revokeToken(uint256,uint256,address,address)": FunctionFragment;
    "setFactoryAddress(address)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "updateAdmin(address)": FunctionFragment;
    "updateAttestation(uint256,string)": FunctionFragment;
    "updateDelegate(uint256)": FunctionFragment;
    "updateSociety(string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addSociety"
      | "issueAttestation"
      | "revokeToken"
      | "setFactoryAddress"
      | "supportsInterface"
      | "updateAdmin"
      | "updateAttestation"
      | "updateDelegate"
      | "updateSociety"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addSociety",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "issueAttestation",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeToken",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setFactoryAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAttestation",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDelegate",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSociety",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "addSociety", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "issueAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFactoryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDelegate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSociety",
    data: BytesLike
  ): Result;

  events: {
    "AdminUpdated(address,address)": EventFragment;
    "AttestationUpdated(address,uint256,string)": EventFragment;
    "DelegatesUpdated(address,uint256)": EventFragment;
    "Issued(address,address,address,uint256,uint256)": EventFragment;
    "Revoked(uint256,uint256,address,address)": EventFragment;
    "SocietyUpdated(address,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AttestationUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DelegatesUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Issued"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Revoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SocietyUpdated"): EventFragment;
}

export interface AdminUpdatedEventObject {
  society: string;
  admin: string;
}
export type AdminUpdatedEvent = TypedEvent<
  [string, string],
  AdminUpdatedEventObject
>;

export type AdminUpdatedEventFilter = TypedEventFilter<AdminUpdatedEvent>;

export interface AttestationUpdatedEventObject {
  society: string;
  attestationId: BigNumber;
  uri: string;
}
export type AttestationUpdatedEvent = TypedEvent<
  [string, BigNumber, string],
  AttestationUpdatedEventObject
>;

export type AttestationUpdatedEventFilter =
  TypedEventFilter<AttestationUpdatedEvent>;

export interface DelegatesUpdatedEventObject {
  society: string;
  attestationId: BigNumber;
}
export type DelegatesUpdatedEvent = TypedEvent<
  [string, BigNumber],
  DelegatesUpdatedEventObject
>;

export type DelegatesUpdatedEventFilter =
  TypedEventFilter<DelegatesUpdatedEvent>;

export interface IssuedEventObject {
  society: string;
  recipient: string;
  issuedBy: string;
  attestationId: BigNumber;
  tokenId: BigNumber;
}
export type IssuedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  IssuedEventObject
>;

export type IssuedEventFilter = TypedEventFilter<IssuedEvent>;

export interface RevokedEventObject {
  tokenId: BigNumber;
  attestationId: BigNumber;
  revokedBy: string;
  _owner: string;
}
export type RevokedEvent = TypedEvent<
  [BigNumber, BigNumber, string, string],
  RevokedEventObject
>;

export type RevokedEventFilter = TypedEventFilter<RevokedEvent>;

export interface SocietyUpdatedEventObject {
  society: string;
  uri: string;
}
export type SocietyUpdatedEvent = TypedEvent<
  [string, string],
  SocietyUpdatedEventObject
>;

export type SocietyUpdatedEventFilter = TypedEventFilter<SocietyUpdatedEvent>;

export interface IMetaHolder extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IMetaHolderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addSociety(
      society: PromiseOrValue<string>,
      uri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    issueAttestation(
      attestationId: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      issuedBy: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeToken(
      tokenId: PromiseOrValue<BigNumberish>,
      attestationId: PromiseOrValue<BigNumberish>,
      _owner: PromiseOrValue<string>,
      revokedBy: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFactoryAddress(
      factory: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    updateAdmin(
      admin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateAttestation(
      attestationId: PromiseOrValue<BigNumberish>,
      uri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateDelegate(
      attestationId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateSociety(
      uri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addSociety(
    society: PromiseOrValue<string>,
    uri: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  issueAttestation(
    attestationId: PromiseOrValue<BigNumberish>,
    tokenId: PromiseOrValue<BigNumberish>,
    recipient: PromiseOrValue<string>,
    issuedBy: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeToken(
    tokenId: PromiseOrValue<BigNumberish>,
    attestationId: PromiseOrValue<BigNumberish>,
    _owner: PromiseOrValue<string>,
    revokedBy: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFactoryAddress(
    factory: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  updateAdmin(
    admin: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateAttestation(
    attestationId: PromiseOrValue<BigNumberish>,
    uri: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateDelegate(
    attestationId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateSociety(
    uri: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addSociety(
      society: PromiseOrValue<string>,
      uri: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    issueAttestation(
      attestationId: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      issuedBy: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeToken(
      tokenId: PromiseOrValue<BigNumberish>,
      attestationId: PromiseOrValue<BigNumberish>,
      _owner: PromiseOrValue<string>,
      revokedBy: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFactoryAddress(
      factory: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    updateAdmin(
      admin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateAttestation(
      attestationId: PromiseOrValue<BigNumberish>,
      uri: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateDelegate(
      attestationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateSociety(
      uri: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AdminUpdated(address,address)"(
      society?: null,
      admin?: null
    ): AdminUpdatedEventFilter;
    AdminUpdated(society?: null, admin?: null): AdminUpdatedEventFilter;

    "AttestationUpdated(address,uint256,string)"(
      society?: null,
      attestationId?: null,
      uri?: null
    ): AttestationUpdatedEventFilter;
    AttestationUpdated(
      society?: null,
      attestationId?: null,
      uri?: null
    ): AttestationUpdatedEventFilter;

    "DelegatesUpdated(address,uint256)"(
      society?: null,
      attestationId?: null
    ): DelegatesUpdatedEventFilter;
    DelegatesUpdated(
      society?: null,
      attestationId?: null
    ): DelegatesUpdatedEventFilter;

    "Issued(address,address,address,uint256,uint256)"(
      society?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      issuedBy?: PromiseOrValue<string> | null,
      attestationId?: null,
      tokenId?: null
    ): IssuedEventFilter;
    Issued(
      society?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      issuedBy?: PromiseOrValue<string> | null,
      attestationId?: null,
      tokenId?: null
    ): IssuedEventFilter;

    "Revoked(uint256,uint256,address,address)"(
      tokenId?: PromiseOrValue<BigNumberish> | null,
      attestationId?: PromiseOrValue<BigNumberish> | null,
      revokedBy?: PromiseOrValue<string> | null,
      _owner?: null
    ): RevokedEventFilter;
    Revoked(
      tokenId?: PromiseOrValue<BigNumberish> | null,
      attestationId?: PromiseOrValue<BigNumberish> | null,
      revokedBy?: PromiseOrValue<string> | null,
      _owner?: null
    ): RevokedEventFilter;

    "SocietyUpdated(address,string)"(
      society?: null,
      uri?: null
    ): SocietyUpdatedEventFilter;
    SocietyUpdated(society?: null, uri?: null): SocietyUpdatedEventFilter;
  };

  estimateGas: {
    addSociety(
      society: PromiseOrValue<string>,
      uri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    issueAttestation(
      attestationId: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      issuedBy: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeToken(
      tokenId: PromiseOrValue<BigNumberish>,
      attestationId: PromiseOrValue<BigNumberish>,
      _owner: PromiseOrValue<string>,
      revokedBy: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFactoryAddress(
      factory: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateAdmin(
      admin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateAttestation(
      attestationId: PromiseOrValue<BigNumberish>,
      uri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateDelegate(
      attestationId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateSociety(
      uri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addSociety(
      society: PromiseOrValue<string>,
      uri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    issueAttestation(
      attestationId: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      recipient: PromiseOrValue<string>,
      issuedBy: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeToken(
      tokenId: PromiseOrValue<BigNumberish>,
      attestationId: PromiseOrValue<BigNumberish>,
      _owner: PromiseOrValue<string>,
      revokedBy: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFactoryAddress(
      factory: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateAdmin(
      admin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateAttestation(
      attestationId: PromiseOrValue<BigNumberish>,
      uri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateDelegate(
      attestationId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateSociety(
      uri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
