import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div className="py-0 px-10">
      <Head>
        <title>Credential Manager App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-center text-3xl'>View list of SBTs</h1>
    </div>
  );
};

export default Home;
