import Header from 'layout/Header';
import type { NextPage } from 'next';
import Head from 'next/head';
import Signature from './Signature';

const Home: NextPage = () => {
  return (
    <div className="py-0 px-10">
      <Head>
        <title>Credential Manager App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Signature />
    </div>
  );
};

export default Home;
