/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MetadataHolder } from "./MetadataHolder";
export * as factories from "./factories";
export { MetadataHolder__factory } from "./factories/MetadataHolder__factory";
