/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Desoc } from "./Desoc";
export * as factories from "./factories";
export { Desoc__factory } from "./factories/Desoc__factory";
