name: main

on:
  push:
    paths:
      - "packages/contracts/**"
  pull_request:
    branches:
      - main
    paths:
      - "packages/contracts/**"
env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      matrix:
        version: [16]
      fail-fast: true

    name: contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd packages/contracts
          forge --version
          yarn install
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd packages/contracts
          forge test -vvv
        id: main
