name: main

on:
  push:
   paths:
        - "apps/contracts/**"
  pull_request:
    branches:
    - main
env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      matrix:
        version: [16]
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd apps/contracts
          forge --version
          cd lib/gsn && yarn install && cd ../..
          yarn install
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd apps/contracts
          cd lib/gsn && yarn install && cd ../..
          forge test -vvv
        id: main
