name: coverage report

on:
  pull_request:
    paths:
      - "packages/contracts/**"

jobs:
  coverage_report:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      # ... Generate LCOV files or download it from a different job
      - name: Generate Test coverage
        run: |
          /usr/bin/sudo apt-get install -y lcov
          forge coverage --report lcov
          lcov --remove lcov.info  -o lcov.info 'test/*' 'script/*'
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v2
        with:
          coverage-files: coverage/lcov.*.info
          minimum-coverage: 90
          artifact-name: contracts-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./
