name: coverage report

on:
  pull_request:
    paths:
      - "packages/contracts/**"

jobs:
  coverage_report:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      # ... Generate LCOV files or download it from a different job
      - name: Generate Test coverage
        run: |
          /usr/bin/sudo apt-get install -y lcov
          cd packages/contracts
          forge coverage --report lcov
          mkdir coverage
          lcov --remove lcov.info  -o coverage/lcov.info 'test/*' 'script/*'
          rm lcov.info
      - name: Reporter
        uses: manarbenkraouda/lcov-reporter-action@v0.3.5.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./packages/contracts/coverage/lcov.info
          lcov-base: ./packages/contracts/coverage/lcov.info
          hide-table: false
      # - name: Report code coverage
      #   uses: zgosalvez/github-actions-report-lcov@v2
      #   with:
      #     coverage-files: coverage/lcov.*.info
      #     minimum-coverage: 90
      #     artifact-name: coverage-report
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     working-directory: packages/contracts
