name: main

on:
  push:
   paths:
        - "apps/web/**"
  pull_request:
    branches:
    - main
env:
  FOUNDRY_PROFILE: ci

jobs:
  lint:
    name: "Lint codebase"
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Lint codebase
        run: yarn lint