name: main

on:
  push:
   paths:
        - "apps/web/**"
  pull_request:
    branches:
    - main
env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      matrix:
        version: [16]
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd apps/contracts
          forge --version
          yarn install
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd apps/contracts
          forge test -vvv
        id: main

  lint:
    name: "Lint codebase"
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Lint codebase
        run: yarn lint