name: main

on:
  push:
   paths:
        - "apps/web/**"
  pull_request:
    branches:
    - main

jobs:
  test:
    name: "Test codebase"
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Integration Test
        run: |
          cd apps/web
          yarn test